/*
  This file is automatically generated. Any changes will be overwritten.
  Modify app.module.ts instead.
*/
import { APP_INITIALIZER } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { FormsModule } from '@angular/forms';
import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';
import { BodyModule } from '@radzen/angular/dist/body';
import { CardModule } from '@radzen/angular/dist/card';
import { ContentContainerModule } from '@radzen/angular/dist/content-container';
import { HeaderModule } from '@radzen/angular/dist/header';
import { SidebarToggleModule } from '@radzen/angular/dist/sidebar-toggle';
import { LabelModule } from '@radzen/angular/dist/label';
import { ProfileMenuModule } from '@radzen/angular/dist/profilemenu';
import { GravatarModule } from '@radzen/angular/dist/gravatar';
import { SidebarModule } from '@radzen/angular/dist/sidebar';
import { PanelMenuModule } from '@radzen/angular/dist/panelmenu';
import { FooterModule } from '@radzen/angular/dist/footer';
import { ContentModule } from '@radzen/angular/dist/content';
import { HeadingModule } from '@radzen/angular/dist/heading';
import { GridModule } from '@radzen/angular/dist/grid';
import { TemplateFormModule } from '@radzen/angular/dist/template-form';
import { TextBoxModule } from '@radzen/angular/dist/textbox';
import { ButtonModule } from '@radzen/angular/dist/button';
import { DropDownModule } from '@radzen/angular/dist/dropdown';
import { FormModule } from '@radzen/angular/dist/form';
import { PasswordModule } from '@radzen/angular/dist/password';
import { LoginModule } from '@radzen/angular/dist/login';
import { HtmlModule } from '@radzen/angular/dist/html';
import { DropDownDataGridModule } from '@radzen/angular/dist/dropdown-datagrid';
import { DatePickerModule } from '@radzen/angular/dist/datepicker';
import { NumericModule } from '@radzen/angular/dist/numeric';
import { SharedModule } from '@radzen/angular/dist/shared';
import { NotificationModule } from '@radzen/angular/dist/notification';
import { DialogModule } from '@radzen/angular/dist/dialog';

import { ConfigService, configServiceFactory } from './config.service';
import { AppRoutes } from './app.routes';
import { AppComponent } from './app.component';
import { CacheInterceptor } from './cache.interceptor';
export { AppComponent } from './app.component';
import { OsobaComponent } from './osoba/osoba.component';
import { AddOsobaComponent } from './add-osoba/add-osoba.component';
import { EditOsobaComponent } from './edit-osoba/edit-osoba.component';
import { KlasaComponent } from './klasa/klasa.component';
import { AddKlasaComponent } from './add-klasa/add-klasa.component';
import { EditKlasaComponent } from './edit-klasa/edit-klasa.component';
import { NauczycielComponent } from './nauczyciel/nauczyciel.component';
import { AddNauczycielComponent } from './add-nauczyciel/add-nauczyciel.component';
import { EditNauczycielComponent } from './edit-nauczyciel/edit-nauczyciel.component';
import { ApplicationUsersComponent } from './application-users/application-users.component';
import { AddApplicationRoleComponent } from './add-application-role/add-application-role.component';
import { ApplicationRolesComponent } from './application-roles/application-roles.component';
import { RegisterApplicationUserComponent } from './register-application-user/register-application-user.component';
import { EditApplicationUserComponent } from './edit-application-user/edit-application-user.component';
import { AddApplicationUserComponent } from './add-application-user/add-application-user.component';
import { ProfileComponent } from './profile/profile.component';
import { LoginComponent } from './login/login.component';
import { UnauthorizedComponent } from './unauthorized/unauthorized.component';
import { RodzicComponent } from './rodzic/rodzic.component';
import { AddRodzicComponent } from './add-rodzic/add-rodzic.component';
import { EditRodzicComponent } from './edit-rodzic/edit-rodzic.component';
import { UczenComponent } from './uczen/uczen.component';
import { AddUczenComponent } from './add-uczen/add-uczen.component';
import { EditUczenComponent } from './edit-uczen/edit-uczen.component';
import { OcenaComponent } from './ocena/ocena.component';
import { AddOcenaComponent } from './add-ocena/add-ocena.component';
import { EditOcenaComponent } from './edit-ocena/edit-ocena.component';
import { LoginLayoutComponent } from './login-layout/login-layout.component';
import { MainLayoutComponent } from './main-layout/main-layout.component';

import { BazaService } from './baza.service';
import { SecurityService, UserService } from './security.service';
import { SecurityInterceptor } from './security.interceptor';
import { AuthGuard } from './auth.guard';

export const PageDeclarations = [
  OsobaComponent,
  AddOsobaComponent,
  EditOsobaComponent,
  KlasaComponent,
  AddKlasaComponent,
  EditKlasaComponent,
  NauczycielComponent,
  AddNauczycielComponent,
  EditNauczycielComponent,
  ApplicationUsersComponent,
  AddApplicationRoleComponent,
  ApplicationRolesComponent,
  RegisterApplicationUserComponent,
  EditApplicationUserComponent,
  AddApplicationUserComponent,
  ProfileComponent,
  LoginComponent,
  UnauthorizedComponent,
  RodzicComponent,
  AddRodzicComponent,
  EditRodzicComponent,
  UczenComponent,
  AddUczenComponent,
  EditUczenComponent,
  OcenaComponent,
  AddOcenaComponent,
  EditOcenaComponent,
];

export const LayoutDeclarations = [
  LoginLayoutComponent,
  MainLayoutComponent,
];

export const AppDeclarations = [
  ...PageDeclarations,
  ...LayoutDeclarations,
  AppComponent
];

export const AppProviders = [
  {
    provide: HTTP_INTERCEPTORS,
    useClass: CacheInterceptor,
    multi: true
  },
  BazaService,
  UserService,
  SecurityService,
  {
    provide: HTTP_INTERCEPTORS,
    useClass: SecurityInterceptor,
    multi: true
  },
  AuthGuard,
  ConfigService,
  {
    provide: APP_INITIALIZER,
    useFactory: configServiceFactory,
    deps: [ConfigService],
    multi: true
  }
];

export const AppImports = [
  BrowserModule,
  BrowserAnimationsModule,
  FormsModule,
  HttpClientModule,
  BodyModule,
  CardModule,
  ContentContainerModule,
  HeaderModule,
  SidebarToggleModule,
  LabelModule,
  ProfileMenuModule,
  GravatarModule,
  SidebarModule,
  PanelMenuModule,
  FooterModule,
  ContentModule,
  HeadingModule,
  GridModule,
  TemplateFormModule,
  TextBoxModule,
  ButtonModule,
  DropDownModule,
  FormModule,
  PasswordModule,
  LoginModule,
  HtmlModule,
  DropDownDataGridModule,
  DatePickerModule,
  NumericModule,
  SharedModule,
  NotificationModule,
  DialogModule,
  AppRoutes
];
