/*
  This file is automatically generated. Any changes will be overwritten.
  Modify edit-obecnosc.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { TemplateFormComponent } from '@radzen/angular/dist/template-form';
import { LabelComponent } from '@radzen/angular/dist/label';
import { CheckBoxComponent } from '@radzen/angular/dist/checkbox';
import { DropDownDataGridComponent } from '@radzen/angular/dist/dropdown-datagrid';
import { ButtonComponent } from '@radzen/angular/dist/button';

import { ConfigService } from '../config.service';

import { BazaService } from '../baza.service';
import { SecurityService } from '../security.service';

export class EditObecnoscGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('form0') form0: TemplateFormComponent;
  @ViewChild('czyBylLabel') czyBylLabel: LabelComponent;
  @ViewChild('czyByl') czyByl: CheckBoxComponent;
  @ViewChild('uczenIdLabel') uczenIdLabel: LabelComponent;
  @ViewChild('uczenId') uczenId: DropDownDataGridComponent;
  @ViewChild('dataOpisIdLabel') dataOpisIdLabel: LabelComponent;
  @ViewChild('dataOpisId') dataOpisId: DropDownDataGridComponent;
  @ViewChild('button1') button1: ButtonComponent;
  @ViewChild('button2') button2: ButtonComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;

  baza: BazaService;

  security: SecurityService;
  obecnosc: any;
  getByUczensForuczen_idResult: any;
  getByDataOpisFordata_opis_idResult: any;
  getUczensForuczen_idPageSize: any;
  getUczensForuczen_idResult: any;
  getUczensForuczen_idCount: any;
  getDataOpisFordata_opis_idPageSize: any;
  getDataOpisFordata_opis_idResult: any;
  getDataOpisFordata_opis_idCount: any;
  parameters: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

    this.baza = this.injector.get(BazaService);
    this.security = this.injector.get(SecurityService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    if (this._subscription) {
      this._subscription.unsubscribe();
    }
  }


  load() {
    this.baza.getObecnoscByocenaId(null, this.parameters.ocena_id)
    .subscribe((result: any) => {
      this.obecnosc = result;

      if (this.obecnosc.uczen_id != null) {
              this.baza.getUczenByuczenId(null, this.obecnosc.uczen_id)
        .subscribe((result: any) => {
              this.getByUczensForuczen_idResult = result;
        }, (result: any) => {
      
        });
      }

      if (this.obecnosc.data_opis_id != null) {
              this.baza.getDataOpiBydataOpisId(null, this.obecnosc.data_opis_id)
        .subscribe((result: any) => {
              this.getByDataOpisFordata_opis_idResult = result;
        }, (result: any) => {
      
        });
      }
    }, (result: any) => {

    });

    this.getUczensForuczen_idPageSize = 10;

    this.baza.getUczens(null, this.getUczensForuczen_idPageSize, 0, null, true, null, null, null)
    .subscribe((result: any) => {
      this.getUczensForuczen_idResult = result.value;

      this.getUczensForuczen_idCount = result['@odata.count'];
    }, (result: any) => {

    });

    this.getDataOpisFordata_opis_idPageSize = 10;

    this.baza.getDataOpis(null, this.getDataOpisFordata_opis_idPageSize, 0, null, true, null, null, null)
    .subscribe((result: any) => {
      this.getDataOpisFordata_opis_idResult = result.value;

      this.getDataOpisFordata_opis_idCount = result['@odata.count'];
    }, (result: any) => {

    });
  }

  form0Submit(event: any) {
    this.baza.updateObecnosc(`Uczen,DataOpi`, this.parameters.ocena_id, event)
    .subscribe((result: any) => {
      if (this.dialogRef) {
        this.dialogRef.close();
      } else {
        this._location.back();
      }
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: `Error`, detail: `Unable to update Obecnosc` });
    });
  }

  uczen_idLoadData(event: any) {
    this.baza.getUczens(`${event.filter}`, event.top, event.skip, `${event.orderby}`, true, null, null, null)
    .subscribe((result: any) => {
      this.getUczensForuczen_idResult = result.value;

      this.getUczensForuczen_idCount = result['@odata.count'];
    }, (result: any) => {

    });
  }

  data_opis_idLoadData(event: any) {
    this.baza.getDataOpis(`${event.filter}`, event.top, event.skip, `${event.orderby}`, true, null, null, null)
    .subscribe((result: any) => {
      this.getDataOpisFordata_opis_idResult = result.value;

      this.getDataOpisFordata_opis_idCount = result['@odata.count'];
    }, (result: any) => {

    });
  }

  button2Click(event: any) {
    if (this.dialogRef) {
      this.dialogRef.close();
    } else {
      this._location.back();
    }
  }
}
